### ISSUE TITLE
iOS 8.4

### ISSUE THREAD

**Issue by gustav77** [richpixel/SongPickerANE#12]
Hi richpixel,

just tried to build a new release of our app with your ANE using iOS 8.4 SDK. Got the following error message:

Error: libGoViralAPI.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

Please help, thank you
Günter

**Comment by richpixel** [comment]
Hi, 
Do you have any other ANE's in your project? I don't remember seeing the 'libGoViralAPI' before. I believe the universal iOS issue was fixed in issue #11

**Comment by gustav77** [comment]
You are right, sorry.
